#!/bin/bash
# the first script of case scripts


echo 
echo " please select the any options below"
echo " a= display date and time "
echo " b= list files and directories "
echo " c= lists the users logged in "
echo " d=check the system uptime "
echo
       read choices
       case $choices in
a) date;;
b) ls;;
c) who;;
d) uptime;;
  esac

